name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" > assets/assets/.env
          echo "APP_ID=${{ secrets.APP_ID }}" >> assets/assets/.env
          echo "MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }}" >> assets/assets/.env
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> assets/assets/.env
          echo "AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }}" >> assets/assets/.env
          echo "STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}" >> assets/assets/.env
          echo "MEASUREMENT_ID=${{ secrets.MEASUREMENT_ID }}" >> assets/assets/.env

      - name: Build web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
